apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterrules.enforcement.globo.com
spec:
  group: enforcement.globo.com
  names:
    kind: ClusterRule
    listKind: ClusterRuleList
    plural: clusterrules
    singular: clusterrule
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          properties:
            enforcements:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  repo:
                    type: string
                  path:
                    type: string
                  namespace:
                    type: string
                  helm:
                    type: object
                    properties:
                      parameters:
                        type: object
            source:
              type: object
              properties:
                rancher:
                  type: object
                  properties:
                    filters:
                      type: object
                    labels:
                      type: object
                    ignore:
                      type: array
                      items:
                        type: string
            triggers:
              type: object
              properties:
                beforeInstall:
                  type: object
                  properties:
                    endpoint:
                      type: string
                    timeout:
                      type: integer
                afterInstall:
                  type: object
                  properties:
                    endpoint:
                      type: string
                    timeout:
                      type: integer
          required:
            - enforcements
            - source
        status:
          type: object
      required:
        - apiVersion
        - kind
        - spec
  versions:
    - name: v1beta1
      served: true
      storage: true
