---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "enforcement.fullname" . }}-account
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "enforcement.fullname" . }}-role-cluster
rules:

  - apiGroups: [enforcement.globo.com]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]

  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "enforcement.fullname" . }}-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "enforcement.fullname" . }}-role-cluster
subjects:
  - kind: ServiceAccount
    name: {{ include "enforcement.fullname" . }}-account
    namespace: {{ .Release.Namespace }}
---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "enforcement.fullname" . }}-role-namespaced
  namespace: {{ .Release.Namespace }}
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [enforcement.globo.com]
    resources: [kopfpeerings]
    verbs: [list, watch, patch, get]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create]

  - apiGroups: [""]
    resources: [events]
    verbs: [create]


  # Application: watching & handling for the custom resource we declare.
  - apiGroups: [enforcement.globo.com]
    resources: [clusterrules]
    verbs: [list, watch, patch, update, get]

  - apiGroups: [enforcement.globo.com]
    resources: ["clusterrules/status"]
    verbs: [patch, update, create]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [get, watch, list]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "enforcement.fullname" . }}-rolebinding-namespaced
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "enforcement.fullname" . }}-role-namespaced
subjects:
  - kind: ServiceAccount
    name: {{ include "enforcement.fullname" . }}-account