image:
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

spec:
  sync:
    minutes: 1 
  argo:
    host: argocd-server.argocd.svc.cluster.local
  rancher:
    host: ""
  enforcement:
    secret: enforcement-secret
    core:
      repo: ""
      path: apps 
      name: enforcement-application
