apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "enforcement.fullname" . }}-job 
  labels:
    {{- include "enforcement.labels" . | nindent 4 }}
spec:
  schedule: "*/{{ .Values.spec.sync.minutes}} * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ .Chart.Name }}
              image: "rodrigoribeiro/enforcement-service:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources: 
                limits:
                    cpu: {{ .Values.resources.limits.cpu}}
                    memory: {{ .Values.resources.limits.memory}}
                requests:
                    cpu: {{ .Values.resources.requests.cpu}}
                    memory: {{ .Values.resources.requests.memory}}
              env:
                - name: RANCHER_URL
                  value: "https://{{.Values.spec.rancher.host}}"
                - name: ARGO_URL
                  value:  "https://{{.Values.spec.argo.host}}"
                - name: ENFORCEMENT_CORE_REPO
                  value: {{.Values.spec.enforcement.core.repo}}
                - name: ENFORCEMENT_CORE_PATH
                  value: {{.Values.spec.enforcement.core.path}}
                - name: ENFORCEMENT_NAME
                  value:  {{.Values.spec.enforcement.core.name}}
                - name: RANCHER_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{.Values.spec.enforcement.secret}}
                      key: rancher.token
                - name: ARGO_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: {{.Values.spec.enforcement.secret}}
                      key: argo.username
                - name: ARGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: {{.Values.spec.enforcement.secret}}
                      key: argo.password
          restartPolicy: OnFailure
                {{- with .Values.nodeSelector }}
          nodeSelector:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.affinity }}
          affinity:
                {{- toYaml . | nindent 8 }}
            {{- end }}
            {{- with .Values.tolerations }}
          tolerations:
                {{- toYaml . | nindent 8 }}
            {{- end }}
