image:
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: 
  limits:
    cpu: 200m
    memory: 228Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

spec:
  argo:
    host: argocd-server.argocd.svc.cluster.local
  enforcement:
    secret: enforcement-secret
